app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_login import (LoginManager, login_required, login_user,
                         current_user, logout_user, UserMixin)
                         
from werkzeug import check_password_hash, generate_password_hash
from sqlalchemy import func, desc

from app import app
from app import db
from app.users.forms import RegisterForm, LoginForm, DataForm, SettingsForm, ListForm, PartnerForm
from app.users.models import User, Account, ExpenseList
from app.users.decorators import requires_login

from utils import check_balances
mod = Blueprint('users', __name__, url_prefix='/users')  

login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message = u"Please log in to access this page."
login_manager.refresh_view = "reauth"
login_manager.init_app(app)
login_manager.login_view = "/login/"
login_manager.setup_app(app)


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

@login_manager.token_loader
def load_token(token):
    data = login_serializer.loads(token)
    user = load_user(data[0])
    if user and data[1] == user.password:
        return user
    else: return None
        
@mod.route('/me/')
def home():
    g.user=None
    user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])
        flash("user is logged")
    return render_template("index.html", guser=g.user)
    
@mod.route('/profile/', methods=['GET', 'POST'])
@requires_login
def profile():
    user = User.query.filter_by(id=session['user_id']).first()
    p1 = User.query.filter_by(email=user.partner1_email).first()
    p2 = User.query.filter_by(email=user.partner2_email).first()
    
    lists = ExpenseList.query.filter_by(user_id=session['user_id']).all()            
    if p1: 
        lists_p1 = ExpenseList.query.filter_by(user_id=p1.id).all()
        lists = lists + lists_p1
    if p2: 
        lists_p2 = ExpenseList.query.filter_by(user_id=p2.id).all()
        lists = lists + lists_p2
    
    unique_listnames = list(set([l.list_name for l in lists]))
    
    form = DataForm(request.form)    
    if form.validate_on_submit():
        # Edit an individual entry    
        edit_data = Account.query.filter_by(edit=True).first()
        if edit_data:   
            edit_data.date = form.date.data
            edit_data.spent = form.amount.data
            edit_data.description = form.description.data
            edit_data.edit = False
            db.session.add(edit_data)
            db.session.commit()
        else:
            data = Account(user_id=session['user_id'], list_name=user.current_list, 
                           user_name=user.name, date=form.date.data, description=form.description.data, \
                           spent=form.amount.data, edit=False)
            db.session.add(data)
            db.session.commit()
            
            unpay_lists = ExpenseList.query.filter_by(user_id=session['user_id'],list_name=user.current_list).all()

            if p1: 
                unpay_lists_p1 = ExpenseList.query.filter_by(user_id=p1.id,list_name=user.current_list).all()
                unpay_lists = unpay_lists +  unpay_lists_p1

            if p2: 
                unpay_lists_p2 = ExpenseList.query.filter_by(user_id=p2.id,list_name=user.current_list).all()
                unpay_lists = unpay_lists +  unpay_lists_p2
            
            for li in unpay_lists:
                if li.payed:
                    li.payed = False
                    db.session.add(li)
                    db.session.commit()
                if li.received:
                    li.received = False 
                    db.session.add(li)   
                    db.session.commit()  
        return redirect(url_for('users.profile'))
    
    # Save list as
    form_save = ListForm(request.form)
    if form_save.validate_on_submit():            
        # Change list name in all entries in current list
        list_all = Account.query.filter_by(user_id=session['user_id'], list_name=user.current_list).all()
        if p1:
            list_p1 = Account.query.filter_by(user_id=p1.id, list_name=user.current_list).all()
            list_all = list_all + list_p1
        if p2:
            list_p2 = Account.query.filter_by(user_id=p2.id, list_name=user.current_list).all()
            list_all = list_all + list_p2
                 
        for li in list_all:
            li.list_name = form_save.list_name.data
            db.session.add(li)
            db.session.commit()
        
        # Add list
        list_u = ExpenseList.query.filter_by(user_id=session['user_id'],list_name="new").first()
        new_list_u = ExpenseList(user_id=session['user_id'], list_name=form_save.list_name.data, \
                            archived=True, payed=list_u.payed, received=list_u.received)
        db.session.add(new_list_u)                      
        db.session.commit()      
        
        list_u.payed = False
        db.session.add(list_u)
        db.session.commit()
        
        if p1:
            list_p1 = ExpenseList.query.filter_by(user_id=p1.id,list_name="new").first()
            new_list_p1 = ExpenseList(user_id=p1.id, list_name=form_save.list_name.data, \
                               archived=True, payed=list_p1.payed, received=list_p1.received)
            db.session.add(new_list_p1)
            db.session.commit()
            
            list_p1.payed = False
            db.session.add(list_p1)
            db.session.commit()
            
        if p2: 
            list_p2 = ExpenseList.query.filter_by(user_id=p2.id,list_name="new").first()
            new_list_p2 = ExpenseList(user_id=p2.id, list_name=form_save.list_name.data, \
                               archived=True, payed=list_p2.payed, received=list_p2.received)
            db.session.add(new_list_p2)
            db.session.commit()
                
            list_p2.payed = False
            db.session.add(list_p2)
            db.session.commit()
                
        user.current_list = form_save.list_name.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.profile'))
              
    entries = Account.query.filter_by(user_id=session['user_id'], list_name=user.current_list) \
                            .order_by(desc(Account.trans_id)).all()
    bal = check_balances(current_list=user.current_list)
    
    if p1:
        p1_entries = Account.query.filter_by(user_id=p1.id, list_name=user.current_list) \
                                   .order_by(desc(Account.trans_id)).all()
        entries = entries + p1_entries
    if p2:
        p2_entries = Account.query.filter_by(user_id=p2.id, list_name=user.current_list) \
                                  .order_by(desc(Account.trans_id)).all()
        entries = entries + p2_entries
            
    return render_template("users/profile.html", user=user, form=form, lists=lists, unique_listnames=unique_listnames, \
           form_save = form_save, entries=entries, bal=bal, p1=p1, p2=p2, guser=g.user)
 
@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])
 
@mod.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id
            login_user(user, remember=form.remember.data)
            return redirect(url_for('users.profile'))
        flash('Wrong email or password', 'login-error')
    return render_template("users/login.html", form=form)
          
#@mod.route('/login/', methods=['GET', 'POST'])
#def login():
#    form = LoginForm(request.form)
#    if form.validate_on_submit():
#        user = User.query.filter_by(email=form.email.data).first()
#        if user and check_password_hash(user.password, form.password.data):
#            session['user_id'] = user.id
#            flash('Welcome %s' % user.name)
#            return redirect(url_for('users.profile'))
#        flash('Wrong email or password', 'login-error')
#    return render_template("users/login.html", form=form)
    
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        check_user = User.query.filter_by(email=form.email.data).first()
        if check_user: 
            flash('A user with email %s already exists.' % form.email.data, "unique-user")
        else:
            user = User(name=form.name.data, email=form.email.data, \
                        password=generate_password_hash(form.password.data))
            db.session.add(user)
            db.session.commit()
            session['user_id'] = user.id
            flash('Thanks for registering')
            
            first_list = ExpenseList(user_id=session['user_id'], list_name="new")
            db.session.add(first_list)
            db.session.commit()
            return redirect(url_for('users.profile'))
        
    return render_template("users/register.html", form=form)

@mod.route('/logout')
@requires_login
def logout():
    logout_user()
    session.pop('user_id', None)
    session.clear()
    flash('You were succesfully logged out.')
    return redirect(url_for('users.home'))

@requires_login
@mod.route('/delete/<int:entry_id>')
def delete_entry(entry_id):
    trans = Account.query.filter_by(trans_id=entry_id).first()
    if trans.user_id == session['user_id']:
        db.session.delete(trans)
        db.session.commit()
    else: flash('Oops, you can only delete your own entries.', 'delete')
    return redirect(url_for('users.profile'))

@requires_login
@mod.route('/edit/<int:entry_id>')
def edit_entry(entry_id):

app/templates/about.html
{% extends "base.html" %}
{% block headtitle %} - About{% endblock %}
{% block title %} Qomon{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<img src="{{ url_for('static', filename='img/front.jpg') }}" 
		     width=40% height=40% class="img-circle img-responsive col-centered" >

		<h3> Qomon is an application developed to help couples or small groups 
			keep track of their common expenses. 
		</h3>
		<h3> If you and your partner / roommate / friend / colleague spend money on 
			 common items such as groceries, gifts, utility bills, etc., but you 
			 use your own money to pay for them, you may want to know how much you 
			 owe each other at the end of the month. This is where Qomon comes in.
		</h3>
		<h3> You can add up to two partners! Just add your partner's email on the 
			settings page, ask your partner to add yours, <em>et Voil&agrave</em>.
		</h3>
		<h3> Qomon was developed by Javiera Guedes, feel free to send her your 
			comments or questions to 
			<a href="mailto:javierahermosa@yahoo.com">this email</a> address. 
		</h3>
	</div> <!-- column -->
</div> <!--row-->


{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
{s% block head %}

HOLA HOLA HOLA HOLA
	<title>Qomon{% block headtitle %}{% endblock %}</title>
 	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
 	<meta name="description" content="">
 	<meta name="keywords" content="">
 	<meta name="author" content="Javiera Guedes">
 	<meta charset="utf-8">
	
	<link type="text/css" rel="stylesheet" 
		  href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
	<link type="text/css" rel="stylesheet" 
		  href="{{ url_for('static', filename='css/my.css') }}" />
	<link type="text/css" rel="stylesheet" 
	  	  href="{{ url_for('static', filename='css/datepicker.css') }}" />
	<link rel="shortcut icon" 
	      href="{{ url_for('static', filename='ico/qomon.ico') }}">		
	<link rel='stylesheet' type='text/css' 
		  href='http://fonts.googleapis.com/css?family=Share+Tech+Mono' > 	
 {% endblock %}
</head>
	
 <body onunload="unloadP('thispage')" onload="loadP('thispage')">
	 <div class="container-narrow">	
		<div class="masthead">
   	 	   <ul class="nav nav-pills pull-right">
				
				<div class="btn-group">
					<a class="btn btn-default" href="{{ url_for('users.about') }}">About</a>
			 	</div>
				
			 	{% if guser %}
				<div class="btn-group">
			    	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			     	  	{{guser.name}} <span class="caret"></span>
			   	 	</button>
			   		<ul class="dropdown-menu" role="menu">
			     		<li><a href="{{ url_for('users.profile') }}">My Qomon</a></li>
			 	 		<li><a href="{{ url_for('users.settings') }}">Settings</a></li>
			     		<li class="divider"></li>
			     		<li><a href="{{ url_for('users.logout') }}">Logout</a></li>
			   		</ul>
			 	</div>
			    {% endif %}
			    
				{% if not guser %}
			    <div class="btn-group">
					<a class="btn btn-default" href="{{ url_for('users.login') }}">Log in</a>
		 	  	</div>
			 	{% endif %}
		   </ul>
   	  	 
		  
		   <h2 class="muted"><a href="{{ url_for('users.home') }}">Qomon</a></h2>

   	</div> <!-- masthead -->
	  
	<hr> <!--horizontal line-->

	{% block content %}
	{% endblock %}
	  	  
	{% block footer %}
 	<footer class="footer">
		<p>Qomon is powered by 
			<a href="http://flask.pocoo.org/docs/">Flask</a>,
			<a href="http://getbootstrap.com/">Bootstrap</a>,
			<a href="http://glyphicons.com/"> Glyphicons</a>, and 
			<a href="https://www.heroku.com/">Heroku</a>.
		</p>
		<p>&copy; Javiera Guedes</p>
	</footer>
    {% endblock %}
	
	</div> <!-- container narrow -->  
	
 <!-- javascript -->
	<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap-datepicker.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.tablesorter.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/scrollfix.js') }}"></script>
    
 	<script>
    	$(function(){
    	  	$('.datepicker').datepicker({
    	  		format: 'dd M yyyy',
    	  		autoclose: true
    	  		});
    	  });
    </script>
	
	<script>  
	    $(document).ready(function () {  
	        $('.dropdown-toggle').dropdown();  
	     });  
	</script> 
	   
	<script>  
	   $(function() {
	     $('.table').tablesorter({
	     	cssInfoBlock : "avoid-sort"
	     });
	   });
	</script> 	
	
	 <script>  
	 var $btn2 = $('#popover');
	 $btn2.data('state', 'hover');

	 var enterShow = function () {
	     if ($btn2.data('state') === 'hover') {
	         $btn2.popover('show');
	     }
	 };
	 var exitHide = function () {
	     if ($btn2.data('state') === 'hover') {
	         $btn2.popover('hide');
	     }
	 };

	 var clickToggle = function () {
	     if ($btn2.data('state') === 'hover') {
	         $btn2.data('state', 'pinned');
	     } else {
	         $btn2.data('state', 'hover')
	         $btn.popover('hover');
	     }
	 };

	 $btn2.popover({trigger: 'manual'})
	     .on('mouseenter', enterShow)
	     .on('mouseleave', exitHide)
	     .on('click', clickToggle);
	
	</script> 	
	
	<script type="text/javascript">
	    $(function () {
	        $("[rel='tooltip']").tooltip();
	    });
	</script>
	
	<script>
		
		$(document).ready(function() {
	   	 if (saveformErrors) {
	        	$("[id='save']").modal('show');
	    }
	});

	</script>
			
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block headtitle %} - Home{% endblock %}

{% block content %}

<div class="jumbotron">
	<div class="container">
		<h1>Qomon</h1>
		{% if not guser %}	
		<p class="lead">A free app to help you keep track of common expenses </p>
		<a class="btn btn-large btn-success" href="{{ url_for('users.register') }}">Sign up today!</a>
		{% else %}
		<p class="lead">A free app to help you keep track of common expenses </p>
		<a class="btn btn-large btn-success" href="{{ url_for('users.profile') }}">Go to your account!</a>
		{% endif %}
	</div>
</div> <!-- jumbotron -->
	  
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 col-sm-8 col-xs-8">
    <h2 class="featurette-heading">Tracking common expenses <span class="text-muted"> is now simple</span></h2>
    <p class="lead">Qomon is the perfect tool for couples, roommates, colleagues, or small groups that need to keep track of common expenses. It helps you keep a tab of what each partner spent and tells you how much you owe each other. </p>
  </div>
  <div class="col-md-5 col-sm-4 col-xs-4">
    <img class="featurette-image img-responsive img-circle" src="{{ url_for('static', filename='img/front.jpg') }}" alt="Generic placeholder image">
  </div>
</div>


<hr>  <!--horizontal line-->

<h2 class="text-success"> It's simple! Here is a snippet: </h2>
<h5> &nbsp; </h5>
<div class="container">
	<img src="{{ url_for('static', filename='img/demo.png') }}" 
	     width=100% height=100% class="img-rounded img-responsive col-centered  ImageBorder" >
</div> <!-- class jumbotron -->

<hr>  <!--horizontal line-->


{% endblock %}